// data.js
const data = [
    
  {
    "cropName":"Rice",
    "cropType": "Cereal Crop",
    "region":"High-yielding staple crop. Requires ample water and warm, wet conditions.",
    "weatherConditions": "Warm and wet",
    "temperatureRange": "20-37°C",
    "soilType": "Clayey or loamy soil",
    "waterRequirements": "high",
  
      "high": "8-10 mm/day during active growth and flowering stages",
      "medium": "5-7 mm/day during early and late growth stages",
      "low": "3-5 mm/day during dormancy or non-critical stages",

    "growingSeason": "3-6 months",
    "plantingDepth": "5-7 cm",
    "fertilizerRequirements": "Nitrogen, Phosphorus",
    "pestAndDiseaseSusceptibility": "Blast, Bacterial Leaf Blight",
    "harvestingTime": "3-6 months",
    "cropRotationRecommendations": "Legumes, Millets, Wheat",
    "storageAndPostHarvestHandling": "Proper drying and storage",
    "commonCultivationPractices": "Regular weeding, water management"
  },
  {
    "cropName":"Maize",
    "cropType": "Cereal Crop",
    "region":"Versatile cereal crop. Requires moderate water and warm, sunny conditions.",
    "weatherConditions": "Warm and sunny",
    "temperatureRange": "20-35°C",
    "soilType": "Well-drained loamy soil",
    "waterRequirements": "medium to high",
  
      "high": "5-7 mm/day during peak growth stage",
      "medium": "3-5 mm/day during early and late growth stages",
      "low": "1-3 mm/day during dormant or non-critical stages",

    "growingSeason": "3-4 months",
    "plantingDepth": "5-8 cm",
    "fertilizerRequirements": "Nitrogen, Phosphorus, Potassium",
    "pestAndDiseaseSusceptibility": "Corn borers, Armyworms, Corn smut",
    "harvestingTime": "3-4 months (when ears are fully matured)",
    "cropRotationRecommendations": "Legumes, Small grains, Brassicas",
    "storageAndPostHarvestHandling": "Proper drying and storage of harvested grains",
    "commonCultivationPractices": "Timely sowing, regular irrigation, weed control, and pest management"
  },
  {
    "cropName":"Wheat",
    "cropType": "Cereal Crop",
    "region":"Versatile cereal crop. Thrives in cool and dry climates.",
    "weatherConditions": "Cool and dry",
    "temperatureRange": "15-20°C",
    "soilType": "Well-drained loam soil",
    "waterRequirements": "medium",
 
      "high": "5-7 mm/day during grain-filling stage",
      "medium": "3-5 mm/day during vegetative and reproductive stages",
      "low": "1-3 mm/day during dormancy or non-critical stages",

    "growingSeason": "4-6 months",
    "plantingDepth": "5-7 cm",
    "fertilizerRequirements": "Nitrogen, Phosphorus",
    "pestAndDiseaseSusceptibility": "Rust, Powdery Mildew",
    "harvestingTime": "4-6 months",
    "cropRotationRecommendations": "Legumes, Oilseeds",
    "storageAndPostHarvestHandling": "Threshing and cleaning",
    "commonCultivationPractices": "Proper seed selection, balanced fertilization"
  },
   {
    "cropName":"Pulses",
    "cropType": "Pulses",
    "region":"Protein-rich legumes. Fix nitrogen, enhance soil fertility. Short growingSeason.",
    "weatherConditions": "Warm and moderate",
    "temperatureRange": "20-30°C",
    "soilType": "Well-drained loamy soil",
    "waterRequirements": "low to medium",

      "high": "4-6 mm/day during pod development stage",
      "medium": "2-4 mm/day during vegetative and flowering stages",
      "low": "1-2 mm/day during dormancy or non-critical stages",

    "growingSeason": "2-4 months",
    "plantingDepth": "3-5 cm",
    "fertilizerRequirements": "Nitrogen, Phosphorus, Potassium",
    "pestAndDiseaseSusceptibility": "Pod borers, Anthracnose",
    "harvestingTime": "2-4 months",
    "cropRotationRecommendations": "Cereals, Oilseeds, Sugarcane",
    "storageAndPostHarvestHandling": "Proper drying and storage",
    "commonCultivationPractices": "Crop rotation, intercropping"
  },
 {
    "cropName":"Sugarcane",
    "cropType": "Sugar Crop",
    "region":"Tropical cash crop. high water requirement. Long growing and harvesting season.",
    "weatherConditions": "Hot and humid",
    "temperatureRange": "20-35°C",
    "soilType": "Well-drained loam soil",
    "waterRequirements": "high",

      "high": "8-10 mm/day during active growth and sugar accumulation stages",
      "medium": "5-7 mm/day during vegetative growth stages",
      "low": "3-5 mm/day during dormancy or non-critical stages",

    "growingSeason": "10-18 months",
    "plantingDepth": "5-8 cm",
    "fertilizerRequirements": "Nitrogen, Phosphorus, Potassium",
    "pestAndDiseaseSusceptibility": "Red Rot, Pyrilla, Shoot Borer",
    "harvestingTime": "10-18 months",
    "cropRotationRecommendations": "Legumes, Oilseeds",
    "storageAndPostHarvestHandling": "Proper cutting and storage",
    "commonCultivationPractices": "Regular irrigation, weed control"
  },
   {
    "cropName":"Cotton",
    "cropType": "Fiber Crop",
    "region":"Fiber crop. Requires sunny, warm climate. Pest-resistant varieties available.",
    "weatherConditions": "Warm and sunny",
    "temperatureRange": "25-35°C",
    "soilType": "Well-drained loam soil",
    "waterRequirements": "medium to high",
 
      "high": "6-8 mm/day during peak flowering and boll development stages",
      "medium": "4-6 mm/day during vegetative and fruiting stages",
      "low": "2-4 mm/day during dormancy or non-critical stages",

    "growingSeason": "5-6 months",
    "plantingDepth": "2-3 cm",
    "fertilizerRequirements": "Nitrogen, Phosphorus",
    "pestAndDiseaseSusceptibility": "Bollworms, Whiteflies",
    "harvestingTime": "5-6 months",
    "cropRotationRecommendations": "Pulses, Cereals",
    "storageAndPostHarvestHandling": "Proper ginning and storage",
    "commonCultivationPractices": "Timely pruning, pest control"
  },
{
    "cropName":"Tea",
    "cropType": "Beverage Crop",
    "region":"Camellia leaves for aromatic beverages. Cool, humid climate preferred.",
    "weatherConditions": "Cool and humid",
    "temperatureRange": "10-30°C",
    "soilType": "Well-drained acidic soil",
    "waterRequirements": "medium",
  
      "high": "4-6 mm/day during active growth and flush production stages",
      "medium": "2-4 mm/day during vegetative growth stages",
      "low": "1-2 mm/day during dormancy or non-critical stages",

    "growingSeason": "Year-round",
    "plantingDepth": "2-4 cm",
    "fertilizerRequirements": "Nitrogen, Phosphorus, Potassium",
    "pestAndDiseaseSusceptibility": "Tea Mosquito Bug, Tea Red Spider Mite",
    "harvestingTime": "Year-round (depending on flushes)",
    "cropRotationRecommendations": "Not applicable",
    "storageAndPostHarvestHandling": "Proper processing and packaging",
    "commonCultivationPractices": "Pruning, proper harvesting techniques"
  },
   {
    "cropName":"Coffee",
    "cropType": "Beverage Crop",
    "region":"Popular caffeinated beverage. Grown in warm, humid regions. Requires shade.",
    "weatherConditions": "Warm and humid",
    "temperatureRange": "15-25°C",
    "soilType": "Well-drained loamy soil",
    "waterRequirements": "medium to high",
  
      "high": "6-8 mm/day during flowering and bean development stages",
      "medium": "4-6 mm/day during vegetative growth and ripening stages",
      "low": "2-4 mm/day during dormancy or non-critical stages",

    "growingSeason": "Year-round",
    "plantingDepth": "3-5 cm",
    "fertilizerRequirements": "Nitrogen, Phosphorus, Potassium",
    "pestAndDiseaseSusceptibility": "Coffee Berry Borer, Leaf Rust",
    "harvestingTime": "Year-round (depending on ripeness)",
    "cropRotationRecommendations": "Not applicable",
    "storageAndPostHarvestHandling": "Proper drying and storage",
    "commonCultivationPractices": "Shade management, pest control"
  },
  //VEGETABLES
  {
 
      "cropName": "Potatoes",
      "cropType": "Vegetable",
      "region": "Cultivated in cool and temperate regions worldwide",
      "weatherConditions": "Cool and temperate",
      "temperatureRange": "15-20°C",
      "soilType": "Well-drained loamy soil",
      "waterRequirements": "medium to high",
      "high": "5-7 mm/day during tuber formation and bulking stages",
      "medium": "3-5 mm/day during vegetative growth and tuber initiation stages",
      "low": "1-3 mm/day during dormancy or non-critical stages",
      "growingSeason": "3-4 months",
      "plantingDepth": "10-15 cm",
      "fertilizerRequirements": "Balanced NPK fertilizers",
      "pestAndDiseaseSusceptibility": "Late blight, Colorado potato beetle",
      "harvestingTime": "3-4 months (when tubers reach desired size)",
      "cropRotationRecommendations": "Legumes, Brassicas",
      "storageAndPostHarvestHandling": "Proper curing and storage in cool and dry conditions",
      "commonCultivationPractices": "Hilling, regular irrigation, weed control"
    },
   {
      "cropName": "Onions",
      "cropType": "Vegetable",
      "region": "Cultivated in various regions across the world",
      "weatherConditions": "Cool to warm",
      "temperatureRange": "15-25°C",
      "soilType": "Well-drained sandy loam soil",
      "waterRequirements": "low to medium",
      "high": "4-6 mm/day during bulb enlargement stage",
      "medium": "2-4 mm/day during vegetative growth and bulbing initiation stages",
      "low": "1-2 mm/day during dormancy or non-critical stages",
      "growingSeason": "3-5 months",
      "plantingDepth": "1-2 cm",
      "fertilizerRequirements": "Balanced NPK fertilizers",
      "pestAndDiseaseSusceptibility": "Onion thrips, Downy mildew",
      "harvestingTime": "3-5 months (when leaves turn yellow and fall over)",
      "cropRotationRecommendations": "Legumes, Brassicas",
      "storageAndPostHarvestHandling": "Curing and storage in a cool and dry place",
      "commonCultivationPractices": "Regular irrigation, weed control, bulb formation management"
    },
 {
      "cropName": "Tomatoes",
      "cropType": "Vegetable",
      "region": "Cultivated in warm and sunny regions worldwide",
      "weatherConditions": "Warm and sunny",
      "temperatureRange": "20-30°C",
      "soilType": "Well-drained loamy soil",
      "waterRequirements": "medium to high",
      "high": "6-8 mm/day during fruit development stage",
      "medium": "4-6 mm/day during vegetative growth and flowering stages",
      "low": "2-4 mm/day during dormancy or non-critical stages",
      "growingSeason": "2-3 months",
      "plantingDepth": "1-2 cm",
      "fertilizerRequirements": "Balanced NPK fertilizers",
      "pestAndDiseaseSusceptibility": "Tomato hornworm, Early blight",
      "harvestingTime": "2-3 months (when fruits reach desired color and size)",
      "cropRotationRecommendations": "Legumes, Brassicas",
      "storageAndPostHarvestHandling": "Harvest at the mature-green stage, store at room temperature",
      "commonCultivationPractices": "Stake or cage plants, regular irrigation, pest control"
    },
  {
      "cropName": "Cauliflower",
      "cropType": "Vegetable",
      "region": "Cultivated in cool and mild regions worldwide",
      "weatherConditions": "Cool and mild",
      "temperatureRange": "15-25°C",
      "soilType": "Well-drained loamy soil",
      "waterRequirements": "medium to high",
      "high": "5-7 mm/day during head formation stage",
      "medium": "3-5 mm/day during vegetative growth and curd initiation stages",
      "low": "1-3 mm/day during dormancy or non-critical stages",
      "growingSeason": "2-3 months",
      "plantingDepth": "1-2 cm",
      "fertilizerRequirements": "Balanced NPK fertilizers",
      "pestAndDiseaseSusceptibility": "Cabbage worms, Downy mildew",
      "harvestingTime": "2-3 months (when curds are compact and firm)",
      "cropRotationRecommendations": "Legumes, Brassicas",
      "storageAndPostHarvestHandling": "Immediate cooling and storage in a cool place",
      "commonCultivationPractices": "Regular irrigation, pest control, blanching for white curds"
    },
 {
      "cropName": "Cabbage",
      "cropType": "Vegetable",
      "region": "Cultivated in cool and mild regions worldwide",
      "weatherConditions": "Cool and mild",
      "temperatureRange": "15-25°C",
      "soilType": "Well-drained loamy soil",
      "waterRequirements": "medium to high",
      "high": "5-7 mm/day during head formation stage",
      "medium": "3-5 mm/day during vegetative growth and head initiation stages",
      "low": "1-3 mm/day during dormancy or non-critical stages",
      "growingSeason": "2-3 months",
      "plantingDepth": "1-2 cm",
      "fertilizerRequirements": "Balanced NPK fertilizers",
      "pestAndDiseaseSusceptibility": "Cabbage worms, Clubroot",
      "harvestingTime": "2-3 months (when heads are firm and compact)",
      "cropRotationRecommendations": "Legumes, Brassicas",
      "storageAndPostHarvestHandling": "Immediate cooling and storage in a cool place",
      "commonCultivationPractices": "Regular irrigation, pest control, proper spacing"
    },
{
      "cropName": "Brinjal (Eggplant)",
      "cropType": "Vegetable",
      "region": "Cultivated in warm and sunny regions worldwide",
      "weatherConditions": "Warm and sunny",
      "temperatureRange": "20-35°C",
      "soilType": "Well-drained loamy soil",
      "waterRequirements": "medium to high",
      "high": "5-7 mm/day during fruit development stage",
      "medium": "3-5 mm/day during vegetative growth and flowering stages",
      "low": "1-3 mm/day during dormancy or non-critical stages",
      "growingSeason": "2-4 months",
      "plantingDepth": "1-2 cm",
      "fertilizerRequirements": "Balanced NPK fertilizers",
      "pestAndDiseaseSusceptibility": "Fruit borer, Fusarium wilt",
      "harvestingTime": "2-4 months (when fruits reach desired size and color)",
      "cropRotationRecommendations": "Legumes, Solanaceae family",
      "storageAndPostHarvestHandling": "Store at room temperature",
      "commonCultivationPractices": "Staking or caging, regular irrigation, pest control"
    },
{
      "cropName": "Lady's Finger (Okra)",
      "cropType": "Vegetable",
      "region": "Cultivated in warm and sunny regions worldwide",
      "weatherConditions": "Warm and sunny",
      "temperatureRange": "25-35°C",
      "soilType": "Well-drained loamy soil",
      "waterRequirements": "medium to high",
      "high": "6-8 mm/day during fruit development stage",
      "medium": "4-6 mm/day during vegetative growth and flowering stages",
      "low": "2-4 mm/day during dormancy or non-critical stages",
      "growingSeason": "2-3 months",
      "plantingDepth": "1-2 cm",
      "fertilizerRequirements": "Balanced NPK fertilizers",
      "pestAndDiseaseSusceptibility": "Fruit borer, Yellow vein mosaic virus",
      "harvestingTime": "2-3 months (when pods are tender and immature)",
      "cropRotationRecommendations": "Legumes, Solanaceae family",
      "storageAndPostHarvestHandling": "Best when consumed fresh",
      "commonCultivationPractices": "Regular irrigation, mulching, pest control"
    },

    //FRUITS
   {
        "cropName": "Mangoes",
        "cropType": "Fruits",
        "weatherConditions": "Hot and tropical",
        "temperatureRange": "25-35°C",
        "soilType": "Well-drained sandy soil",
        "waterRequirements": "medium to high",
          "high": "10-15 mm/day during fruit development stage",
          "medium": "6-10 mm/day during vegetative growth stages",
          "low": "3-6 mm/day during dormancy or non-critical stages",
    
        "growingSeason": "5-6 months",
        "plantingDepth": "30-45 cm",
        "fertilizerRequirements": "Balanced NPK fertilizers with micronutrients",
        "pestAndDiseaseSusceptibility": ["Anthracnose", "Fruit flies"],
        "harvestingTime": "5-6 months (when fruits are fully ripe)",
        "cropRotationRecommendations": ["Legumes", "Grasses"],
        "storageAndPostHarvestHandling": "Store at cool temperatures (varies by mango type)",
        "commonCultivationPractices": ["Regular irrigation", "Pruning", "Pest control"],
        "region": "Requires hot and tropical climates with well-drained sandy soil."
      },
    {
        "cropName": "Citrus Fruits",
        "cropType": "Fruits",
        "weatherConditions": "Warm and sunny",
        "temperatureRange": "15-30°C (varies by citrus type)",
        "soilType": "Well-drained loamy soil",
        "waterRequirements": "medium to high",
   
          "high": "8-12 mm/day during fruit development stage",
          "medium": "4-8 mm/day during vegetative growth stages",
          "low": "2-4 mm/day during dormancy or non-critical stages",
    
        "growingSeason": "8-12 months",
        "plantingDepth": "30-45 cm",
        "fertilizerRequirements": "Balanced NPK fertilizers with micronutrients",
        "pestAndDiseaseSusceptibility": ["Citrus leafminer", "Citrus psyllid", "Citrus canker"],
        "harvestingTime": "Varies by citrus type and desired ripeness",
        "cropRotationRecommendations": ["Legumes", "Grasses"],
        "storageAndPostHarvestHandling": "Store at cool temperatures (varies by citrus type)",
        "commonCultivationPractices": ["Regular irrigation", "Pruning", "Pest control"],
        "region": "Prefers warm and sunny conditions with well-drained loamy soil."
      },
    {
        "cropName": "Grapes",
        "cropType": "Fruits",
        "weatherConditions": "Warm and sunny",
        "temperatureRange": "15-35°C (varies by grape variety)",
        "soilType": "Well-drained sandy loam soil",
        "waterRequirements": "medium to high",
        
          "high": "6-10 mm/day during fruit development stage",
          "medium": "4-6 mm/day during vegetative growth stages",
          "low": "2-4 mm/day during dormancy or non-critical stages",
     
        "growingSeason": "4-6 months",
        "plantingDepth": "10-15 cm",
        "fertilizerRequirements": "Balanced NPK fertilizers with micronutrients",
        "pestAndDiseaseSusceptibility": ["Powdery mildew", "Downy mildew"],
        "harvestingTime": "Varies by grape variety and desired ripeness",
        "cropRotationRecommendations": ["Legumes", "Grasses"],
        "storageAndPostHarvestHandling": "Store at cool temperatures",
        "commonCultivationPractices": ["Regular irrigation", "Pruning", "Pest control"],
        "region": "Thrives in warm and sunny regions with well-drained sandy loam soil."
      },
    {
        "cropName": "Guavas",
        "cropType": "Fruits",
        "weatherConditions": "Warm and tropical",
        "temperatureRange": "20-30°C",
        "soilType": "Well-drained loamy soil",
        "waterRequirements": "medium to high",
    
          "high": "6-10 mm/day during fruit development stage",
          "medium": "4-6 mm/day during vegetative growth stages",
          "low": "2-4 mm/day during dormancy or non-critical stages",
      
        "growingSeason": "6-8 months",
        "plantingDepth": "30-45 cm",
        "fertilizerRequirements": "Balanced NPK fertilizers with micronutrients",
        "pestAndDiseaseSusceptibility": ["Guava fruit fly", "Anthracnose"],
        "harvestingTime": "6-8 months (when fruits develop full size and aroma)",
        "cropRotationRecommendations": ["Legumes", "Grasses"],
        "storageAndPostHarvestHandling": "Store in cool and dry conditions",
        "commonCultivationPractices": ["Regular irrigation", "Pruning", "Pest control"],
        "region": "Thrives in warm and tropical regions with well-drained loamy soil."
      },
     {
        "cropName": "Papayas",
        "cropType": "Fruits",
        "weatherConditions": "Warm and tropical",
        "temperatureRange": "20-33°C",
        "soilType": "Well-drained sandy loam soil",
        "waterRequirements": "high",
       
          "high": "10-15 mm/day during fruit development stage",
          "medium": "6-10 mm/day during vegetative growth stages",
          "low": "3-6 mm/day during dormancy or non-critical stages",
       
        "growingSeason": "8-12 months",
        "plantingDepth": "5-10 cm",
        "fertilizerRequirements": "Balanced NPK fertilizers with micronutrients",
        "pestAndDiseaseSusceptibility": ["Papaya mealybug", "Papaya ringspot virus"],
        "harvestingTime": "8-12 months (when fruits are fully mature and show color changes)",
        "cropRotationRecommendations": ["Legumes", "Grasses"],
        "storageAndPostHarvestHandling": "Store at cool temperatures",
        "commonCultivationPractices": ["Regular irrigation", "Pruning", "Pest control"],
        "region": "Requires warm and tropical climate, well-drained sandy loam soil."
      },
   {
        "cropName": "Bananas",
        "cropType": "Fruits",
        "weatherConditions": "Tropical and subtropical",
        "temperatureRange": "20-30°C",
        "soilType": "Well-drained loamy soil",
        "waterRequirements": "high",
        
          "high": "10-15 mm/day during fruit development stage",
          "medium": "6-10 mm/day during vegetative growth stages",
          "low": "3-6 mm/day during dormancy or non-critical stages",

        "growingSeason": "9-12 months",
        "plantingDepth": "15-20 cm",
        "fertilizerRequirements": "Balanced NPK fertilizers with potassium",
        "pestAndDiseaseSusceptibility": ["Panama disease", "Black sigatoka"],
        "harvestingTime": "Varies by banana variety and desired ripeness",
        "cropRotationRecommendations": ["Non-susceptible crops"],
        "storageAndPostHarvestHandling": "Store at cool temperatures",
        "commonCultivationPractices": ["Regular irrigation", "Mulching", "Pest control"],
        "region": "Thrives in tropical and subtropical regions with well-drained loamy soil."
      },
    {
        "cropName": "Apples",
        "cropType": "Fruits",
        "weatherConditions": "Temperate",
        "temperatureRange": "10-25°C (varies by apple variety)",
        "soilType": "Well-drained loamy soil",
        "waterRequirements": "medium to high",
        "high": "6-10 mm/day during fruit development stage",
          "medium": "4-6 mm/day during vegetative growth stages",
          "low": " 2-4 mm/day during dormancy or non-critical stages",
        "growingSeason": "4-7 months",
        "plantingDepth": "30-45 cm",
        "fertilizerRequirements": "Balanced NPK fertilizers with micronutrients",
        "pestAndDiseaseSusceptibility": ["Apple scab", "Codling moth"],
        "harvestingTime": "Varies by apple variety and desired ripeness",
        "cropRotationRecommendations": ["Non-susceptible crops"],
        "storageAndPostHarvestHandling": "Store in cool and controlled atmosphere",
        "commonCultivationPractices": ["Regular irrigation", "Pruning", "Pest control"],
        "region": "Suitable for temperate climates with well-drained loamy soil."
      },
    {
        "cropName": "Pomegranates",
        "cropType": "Fruits",
        "weatherConditions": "Hot and dry",
        "temperatureRange": "25-35°C",
        "soilType": "Well-drained sandy loam soil",
        "waterRequirements": "low to medium",
          "high": "10-12 mm/day during fruit development stage",
          "medium": "6-10 mm/day during vegetative growth stages",
          "low": "3-6 mm/day during dormancy or non-critical stages",
        
        "growingSeason": "6-7 months",
        "plantingDepth": "30-45 cm",
        "fertilizerRequirements": "Balanced NPK fertilizers with micronutrients",
        "pestAndDiseaseSusceptibility": ["Pomegranate butterfly", "Pomegranate fruit borer"],
        "harvestingTime": "6-7 months (when fruits develop deep color and firmness)",
        "cropRotationRecommendations": ["Legumes", "Grasses"],
        "storageAndPostHarvestHandling": "Store in cool and dry conditions",
        "commonCultivationPractices": ["Regular irrigation", "Pruning", "Pest control"],
        "region": "Thrives in hot and dry regions with well-drained sandy loam soil."
      }

    
    
  
  


    // ... more data
  ];
  
  export default data;
  